{
 "title": "Pracitca 8 Dashs",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Ram Usage (App)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=~\"api-auth|api-comms|api-posts|api-reacts\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage (App)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{container=~\"api-auth|api-comms|api-posts|api-reacts\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Traffic (All)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_network_transmit_bytes_total{namespace=\"p8\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Ram Usage (DBs)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=~\"postgres\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage (DBs)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{container=~\"postgres\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}