apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proyect-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    #(/|$)(.*)
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api/v1/usuarios(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: api-auth-svc
            port:
              number: 80
      - path: /api/v1/publicaciones(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: api-posts-svc
            port:
              number: 80
      - path: /api/v1/comentarios(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: api-comms-svc
            port:
              number: 80
      - path: /api/v1/reacciones(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: api-reacts-svc
            port:
              number: 80
  