resources:
- ./ms_posts_deploy.yaml

patches:
- target:
    kind: Deployment
    name: posts-api-deployment
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: posts-api-deployment
    spec:
      template:
        spec:
          containers:
          - name: api-posts
            image: REPOSITORY/IMAGE:TAG