kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: p8-route-auth
spec:
  parentRefs:
    - kind: Gateway
      name: proyect-gateway
  rules:
    - matches:
      - path:
          value: /api/v1/usuarios
      filters:
      - type: URLRewrite
        urlRewrite:
          path:
            type: ReplacePrefixMatch
            replacePrefixMatch: /graphql
      backendRefs:
        - name: api-auth-svc
          port: 80
          namespace: p8
---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: p8-route-reacts
spec:
  parentRefs:
    - kind: Gateway
      name: proyect-gateway
  rules:
    - matches:
      - path:
          value: /api/v1/reacciones
      filters:
      - type: URLRewrite
        urlRewrite:
          path:
            type: ReplacePrefixMatch
            replacePrefixMatch: /
      backendRefs:
        - name: api-reacts-svc
          port: 80
          namespace: p8
---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: p8-route-posts
spec:
  parentRefs:
    - kind: Gateway
      name: proyect-gateway
  rules:
    - matches:
      - path:
          value: /api/v1/publicaciones
      filters:
      - type: URLRewrite
        urlRewrite:
          path:
            type: ReplacePrefixMatch
            replacePrefixMatch: /graphql
      backendRefs:
        - name: api-posts-svc
          port: 80
          namespace: p8
---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: p8-route-comms
spec:
  parentRefs:
    - kind: Gateway
      name: proyect-gateway
  rules:
    - matches:
      - path:
          value: /api/v1/comentarios
      filters:
      - type: URLRewrite
        urlRewrite:
          path:
            type: ReplacePrefixMatch
            replacePrefixMatch: /
      backendRefs:
        - name: api-comms-svc
          port: 80
          namespace: p8
---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: proyect-route-kibana
spec:
  parentRefs:
    - kind: Gateway
      name: proyect-gateway
      namespace: default
  rules:
    - matches:
      - path:
          value: /admin/kibana
      filters:
      - type: URLRewrite
        urlRewrite:
          path:
            type: ReplacePrefixMatch
            replacePrefixMatch: /
      backendRefs:
        - name: kibana-svc
          port: 80
          namespace: elastic-stack
---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: proyect-route-prometheus
spec:
  parentRefs:
    - kind: Gateway
      name: proyect-gateway
      namespace: default
  rules:
    - matches:
      - path:
          value: /admin/prometheus
      filters:
      - type: URLRewrite
        urlRewrite:
          path:
            type: ReplacePrefixMatch
            replacePrefixMatch: /
      backendRefs:
        - name: prometheus-server
          port: 80
          namespace: monitoring